export const BRANDING = {
  platform_name: "CXSAT",
  platform_description: "Plateforme de pilotage de la satisfaction client",
  logo_url: null,
  logo_dark_url: null,
  favicon_url: null,
  color_background: "40 20% 98.5%",
  color_foreground: "0 0% 3.9%",
  color_card: "40 20% 99%",
  color_card_foreground: "0 0% 3.9%",
  color_popover: "0 0% 100%",
  color_popover_foreground: "0 0% 3.9%",
  color_primary: "210 100% 13%",
  color_primary_foreground: "0 0% 98%",
  color_secondary: "32 100% 37%",
  color_secondary_foreground: "0 0% 9%",
  color_accent: "33 74% 62%",
  color_accent_foreground: "0 0% 98%",
  color_muted: "0 0% 96.1%",
  color_muted_foreground: "0 0% 38%",
  color_destructive: "0 84.2% 60.2%",
  color_destructive_foreground: "0 0% 98%",
  color_success: "141 71% 48%",
  color_success_foreground: "0 0% 98%",
  color_warning: "36 100% 50%",
  color_warning_foreground: "0 0% 98%",
  color_border: "0 0% 89.8%",
  color_input: "0 0% 89.8%",
  color_ring: "0 0% 3.9%",
  border_radius: "0.5rem",
  shadow_style: "DEFAULT",
  font_family: "Satoshi",
  font_url: null,
  form_title: "Votre avis compte !",
  form_subtitle: "Notez-nous en 10 secondes après votre passage",
  form_thank_you: "Merci pour votre avis !",
  qr_slogan: "Scannez ce QR Code",
  ussd_help_text: "Pas de connexion internet ?",
  hide_cxsat_branding: false,
};

export type BrandConfigType = typeof BRANDING;
